### ISSUE TITLE
BURP CRITICAL - invalid syntax in timestamp file (/data/myhostname/current/timestamp)

### ISSUE THREAD

**Issue by ymettier** [regilero/check_burp_backup_age#1]
Hello,

I get this error :
```
bash-4.4# python ./check_burp_backup_age.py  -H myhostname -d /data 
BURP CRITICAL - invalid syntax in timestamp file (/data/myhostname/current/timestamp)
```

Let's see the timestamp file :
```
bash-4.4# cat /data/myhostname/current/timestamp
0000010 2018-06-30 17:01:13 +0000
```

OK, let's fix it (I'm in a docker container, where vim is not installed) :
```
bash-4.4# sed -i -e 's/not 3/not 4/g' check_burp_backup_age.py 
```

Now check again :
```
bash-4.4# python ./check_burp_backup_age.py  -H myhostname -d /data 
BURP OK - Last backup is fresh enough: 0 day(s) 16 hour(s) 14 minute(s) (974<1560)
```

I guess you prefer a better fix than mine, because some burp servers will write the date with 3 items when mine has 4. Like maybe `if len[parts] not in [3, 4]` instead of `if 3 not == len[parts]`. Or `if l < 3 or l > 4` where l is `len[parts]`...
I'm not the best pythonist on Earth so maybe you will find a better solution than mine.

Regards

**Comment by regilero** [comment]
Fixed by Your merge Request. CHANGELOG added.
